### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ffffffry** [eigent-ai/eigent#119]
### What version of eigent are you using?

0.0.44

### System information

windows11

### Problem description

更新和安装都会显示无法关闭然后安装失败

### log

.

**Comment by ffffffry** [comment]
<img width="744" height="541" alt="Image" src="https://github.com/user-attachments/assets/bb3dfb12-ee9d-4eb9-ac18-c56e9ca7f6fe" />

**Comment by Pakchoioioi** [comment]
Hi ffffffy, we will fix this issues in 0.0.47 version. Before that would you restart the computer and try to reinstall again.

**Comment by a7m-1st** [comment]
@Pakchoioioi Yes I faced this issue as well, when trying to update to 0.0.46. from .44. Also, after uninstalling the issue was still persisting.

Today managed to install successfully (btw Appdata was still there, even though I uninstalled). Somehow the Agent inference wasn't working (stuck at loading). 

<img width="310" height="124" alt="Image" src="https://github.com/user-attachments/assets/1c4c389d-0256-414f-b27b-a9a017b934be" />

So I tried to delete the app data in /Roaming & /Local and then I can't use the app (back at permissions page). So I had to uninstall and install again. Then it is working fine : )

**Comment by ffffffry** [comment]
> Hi ffffffy, we will fix this issues in 0.0.47 version. Before that would you restart the computer and try to reinstall again.

Ok, I still can't update now but I can use version 0.0.44 to solve the problem normally

**Comment by a7m-1st** [comment]
@ffffffry was your problem solved with the new update?

**Comment by ffffffry** [comment]
> [@ffffffry](https://github.com/ffffffry) was your problem solved with the new update?

<img width="749" height="540" alt="Image" src="https://github.com/user-attachments/assets/60cabde3-e0a8-4ec4-8039-79e227f02ecd" />No, I still can't update to 0.0.48. Is it my problem?

**Comment by a7m-1st** [comment]
May I know from which version you are trying to update ? @ffffffry still from 0.0.44?

**Comment by ffffffry** [comment]
> May I know from which version you are trying to update ? [@ffffffry](https://github.com/ffffffry) still from 0.0.44?

Yes,still 0.0.44

**Comment by a7m-1st** [comment]
Folders:
```
1. %APPDATA%/Roaming/eigent/ - Main User Data
2. %APPDATA%/Local/eigent-updater - Contains the Current & new exe installers
```

<img width="743" height="574" alt="Image" src="https://github.com/user-attachments/assets/869d05cd-99b0-40cf-995b-b56489ad68be" />

With version 0.0.46 just now I faced this issue and these are the steps I did to solve it. The issue is getting caused by (1) for now for some reason.

Removing (1) solved the issue for me, but you have to uninstall Eigent as well. You can try to move (1) to separate folder, then try to install again then try to copy & paste the App Data back to (1) (*No guarantee this will work, Make sure don't have important data saved in app @ffffffry )

**Comment by ffffffry** [comment]
> Folders:
> 
> ```
> 1. %APPDATA%/Roaming/eigent/ - Main User Data
> 2. %APPDATA%/Local/eigent-updater - Contains the Current & new exe installers
> ```
> 
> <img alt="Image" width="743" height="574" src="https://private-user-images.githubusercontent.com/108264625/477920709-869d05cd-99b0-40cf-995b-b56489ad68be.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUxNjE0MzIsIm5iZiI6MTc1NTE2MTEzMiwicGF0aCI6Ii8xMDgyNjQ2MjUvNDc3OTIwNzA5LTg2OWQwNWNkLTk5YjAtNDBjZi05OTViLWI1NjQ4OWFkNjhiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxNFQwODQ1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmVjZTdhYTgwNGVjNDNhNDlkODkzN2RjOTY0ODc4M2ZlMzc4ODlkZWY2Y2JkMzI3ZDc5MmQ0MThkNzU3ZjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6gdA4I8vJXY8AQ_oLc2lKme8hLZImmXT6amWBKCzmyk">
> With version 0.0.46 just now I faced this issue and these are the steps I did to solve it. The issue is getting caused by (1) for now for some reason.
> 
> Removing (1) solved the issue for me, but you have to uninstall Eigent as well. You can try to move (1) to separate folder, then try to install again then try to copy & paste the App Data back to (1) (*No guarantee this will work, Make sure don't have important data saved in app [@ffffffry](https://github.com/ffffffry) )

Ok thank you very much, I have successfully updated to version 0.0.48

**Comment by Wendong-Fan** [comment]
thanks @a7m-1st !
